### ISSUE TITLE
dotted line missing 2x

### ISSUE THREAD

**Issue by kikipluche** [swarmcity/sc-boardwalk#101]
<img width="541" alt="screen shot 2017-03-31 at 14 47 42" src="https://cloud.githubusercontent.com/assets/9036081/24551093/67e528b0-1621-11e7-830c-8abf9378fdc2.png">
<img width="758" alt="screen shot 2017-04-01 at 15 20 20" src="https://cloud.githubusercontent.com/assets/9036081/24579094/c8760aaa-16ee-11e7-9049-4591f806515f.png">

**Comment by bkawk** [comment]
@kikipluche currently the words "restore a backup-fire" do not have an underline, I assume you expect these words to have an underline on hover?

**Comment by kikipluche** [comment]
yes, i have made an issue for that, or you can fix it :-)

**Comment by kikipluche** [comment]
@bkawk no it is always in underline, not only on hover.
