### ISSUE TITLE
Forgotten Password - Make a new account

### ISSUE THREAD

**Issue by bkawk** [swarmcity/sc-boardwalk#109]
Actual behavior:
I return to the app, it prompts me to enter a password, I try but I've forgotten it, i try again a few times but  really have forgotten it. There is no option to make a new account.

Expected behavior:
Let me make a new account if I forgot my password

Steps to reproduce the problem:
Make an account, forget the password, close browser, open browser, try to login again without using the password that you forgot and without clearing the cache and cookies.

**Comment by kikipluche** [comment]
@bkawk the way it is done right now, you can click on the x in the top right corner, then you are asked if you want to delete the user, after clicking yes you can start all over again.
<img width="405" alt="screen shot 2017-04-12 at 16 27 00" src="https://cloud.githubusercontent.com/assets/9036081/24962675/e3e07940-1f9c-11e7-9973-04410882364f.png">

**Comment by bkawk** [comment]
Ah ok I didn't see the X and felt frustrated, I see it now

**Comment by faffydee** [comment]
maybe this is a sign it needs to be something else then the X. Let me think about that. The userjourney was not completed by the user itself, so it's no good :D
