### ISSUE TITLE
extract private key

### ISSUE THREAD

**Issue by kikipluche** [swarmcity/sc-boardwalk#125]
Actual behavior:
no possibility to extract private key

Expected behavior:
a possibility to extract private key

Steps to reproduce the problem:

**Comment by kikipluche** [comment]
this is a very urgent issue , because a lot of user complaints and it is very unconvenient for support to have people create workarounds.

**Comment by sponnet** [comment]
added an exportPrivateKey function to the sc-vault , just needs to be integrated on the profile screen ?
