### ISSUE TITLE
entry flow

### ISSUE THREAD

**Issue by kikipluche** [swarmcity/sc-boardwalk#126]
Actual behavior: if I have SWT on an external wallet (fe myetherwallet) and I want to import it to swarm city, I have to go throught the I have ARC tokens flow.

Expected behavior:
A flow for uploading an external wallet with SWT

Steps to reproduce the problem:
enter - create new - yes, convert my tokens - I have Arcade tokens in an external wallet

<img width="312" alt="screen shot 2017-04-19 at 14 02 21" src="https://cloud.githubusercontent.com/assets/9036081/25179144/e35abe42-2508-11e7-9bf2-51f67d1b1c79.png">

**Comment by kikipluche** [comment]
there is a suggestion from Jenn, since the ARC-wallet flow will become less relevant over time to rethink the whole entrance flows/ https://docs.google.com/document/d/1eF2RB_6O4ISUqesD2vNEVGCVdO7ymmHTYkrgYgwiTO8/edit?ts=58f7c76a

**Comment by kikipluche** [comment]
another remark from testers:Why does "I have ARC in an external wallet not read as a button? Many users overlook it.
<img width="383" alt="screen shot 2017-04-29 at 13 53 25" src="https://cloud.githubusercontent.com/assets/9036081/25555313/3f1db630-2ce3-11e7-95d4-eceba06b3b1a.png">

**Comment by kikipluche** [comment]
another user reply: Use case: I return to swarm.city and want to see the homepage, as I want to get involved (or get to support) and forgot on what page to see this. Current situation: I only get the 'enter your password' phrase (https://swarm.city/#/vault/unlock) and the 'x', no branding, no other message or quick links. When I hit the close button I only get the message 'Forgot your password? The only thing you can do, is completely remove the user from this device and start over. This can not be undone.' Desired outcome: Quicklinks or homepage when hitting close button, added welcoming SC branding on return. (edited)

**Comment by QueenBeeSC** [comment]
This issue has been resolved.  Users can log out and view the website.

**Comment by kikipluche** [comment]
when coming back to swarm.city, i cannot see what account is active, so don't know which pasword to use, is it possible to show the avatar and nickname here?
<img width="1253" alt="screen shot 2017-05-17 at 15 13 36" src="https://cloud.githubusercontent.com/assets/9036081/26155465/8a205780-3b13-11e7-9dda-da442d05bdc8.png">

**Comment by kikipluche** [comment]
@kingflurkel
