### ISSUE TITLE
[proposal] add fullstack ethereum address to currency screen

### ISSUE THREAD

**Issue by DrDBanner** [swarmcity/sc-boardwalk#130]
#### Actual behavior
* the complete address is not visible at all
* you must open your avatar to see it
* seems to be counterintuitive while I understand why this has been done

#### Expected behavior
* click on currency (0.00 SWT)
* See "Send" & "Shortcode"
* See below "Shortcode" as minor information WalletID: 
* Should be fully visible and on click shot to the clipboard

#### Mockup

![Mockup](http://storage9.static.itmages.com/i/17/0420/h_1492683014_8043170_858c860404.png)

**Comment by kikipluche** [comment]
the ethereum addres is shown in the profile view.
