### ISSUE TITLE
typo in delete user

### ISSUE THREAD

**Issue by kikipluche** [swarmcity/sc-boardwalk#145]
...correct the word "off" this device

Matt suggests to change the sentence to: "You're about to remove the user account from this device. This can not be undone."

<img width="942" alt="screen shot 2017-04-28 at 12 19 46" src="https://cloud.githubusercontent.com/assets/9036081/25524994/068c15ea-2c0d-11e7-8972-a616193d022b.png">

**Comment by joshuam10o** [comment]
I don't have write access to the repo, but I think I'll grab this as a warm-up? @kikipluche
