### ISSUE TITLE
show eth balance

### ISSUE THREAD

**Issue by kikipluche** [swarmcity/sc-boardwalk#149]
Actual behavior: people don't know how to check their eth balance

Expected behavior: see eth balance

Steps to reproduce the problem:

**Comment by sophiii** [comment]
@faffydee i am taking this one ?

**Comment by sponnet** [comment]
TODO

- [ ] calculate minimum amount of gas needed to complete 1 full cycle of transactions of 1 deal, and set this as a minimum threshold before being able to start a new deal.
- [ ] idem for doing an item reply

**Comment by sophiii** [comment]
We should also do this where the swtconvertion happens. We should check that the amount of gas used to convert arc to swt is greater than the value of swt that you get.

**Comment by faffydee** [comment]
thx @sophiii

**Comment by kikipluche** [comment]
@sponnet can you do the formatting of the ETH balance

**Comment by faffydee** [comment]
![screen shot 2017-06-12 at 13 04 47](https://user-images.githubusercontent.com/24499354/27031237-c2c6d60c-4f6f-11e7-92bd-c917a549e75b.png)
