### ISSUE TITLE
Deals in sc-profile 

### ISSUE THREAD

**Issue by kikipluche** [swarmcity/sc-boardwalk#177]
done deals, deals I’m engage with, …)

**Comment by kikipluche** [comment]
link to #138 ?

**Comment by kikipluche** [comment]
Sponnet made a sorting / filtering, now only one array remaines. Copy from sc-hashtag

**Comment by kikipluche** [comment]
@kingflurkel

**Comment by kingflurkel** [comment]
For this we can use the sc-hashtag component, just filter it differently.

**Comment by kikipluche** [comment]
ref to  #138
