### ISSUE TITLE
set up GETH / PARTIY nodes on AWS

### ISSUE THREAD

**Issue by sponnet** [swarmcity/sc-boardwalk#189]
Actual behavior:
We still have 1 geth node running to support SHH and blockchain connectivity - tho this is optional, you could use your own nodes to make the app work.
But in the current setup this has 2 drawbacks:
1/ if the SHH node crashes , messages might be lost if everyone only uses this host
2/ if the GETH node is not in sync, transactions may not be picked up, or see an older version of the truth ( ex wrong balances )

Expected behavior:
1/ scale the amount of SHH nodes horizontally depending on the demand - and set up a LB on https://shh.swam.city/
2/ set up parity for TXes ( lighter DB footprint , faster syncing ) on LB https://eth.swarm.city 

Steps to reproduce the problem:

**Comment by kikipluche** [comment]
Issue moved to [swarmcity/infrastructure #1](https://github.com/swarmcity/infrastructure/issues/1) via [**ZenHub**](https://www.zenhub.com/)
