### ISSUE TITLE
Deals can be broken in the frontend by someone stupid/malicious

### ISSUE THREAD

**Issue by joshuam10o** [swarmcity/sc-boardwalk#208]
**Actual behavior:** 
deal may appear complete with the text "this deal has been completed", even though it should technically not be complete, and the UI doesn't change it so that it appears complete.
![2017-06-05-202744_3200x1800_scrot](https://cloud.githubusercontent.com/assets/22443690/26799449/a3995616-4a2d-11e7-90d0-3f062c3aa23a.png)

**Expected behavior:** 
deal should not be marked as complete.

**Steps to reproduce the problem:** 
by manually browsing to .../dealfortwoseeker/... when one is the provider, one can send the whisper message to complete the deal as if they were the seeker.

**Comment by sponnet** [comment]
this will be solved by #188

**Comment by kingflurkel** [comment]
Damn, @joshuam10o wished i saw this before the launch. 
https://github.com/swarmcity/sc-boardwalk/issues/352

**Comment by kingflurkel** [comment]
#352
