### ISSUE TITLE
Geolocation disabled should notify that offers cannot be submitted

### ISSUE THREAD

**Issue by BvL13** [swarmcity/sc-boardwalk#210]
Actual behavior:
When geolocation is disabled the blue checkmark button is disabled. 
Users can type in what they are looking for and the SWT amount but cannot send the information.

Expected behavior:
A) Disable making any offerings and notify user that he has to switch on geolocation to make a request
B) Enable making offerings and when clicking on Blue Checkmark Button notify users that geolocation is disabled and his request cannot proceed unless he turns on Geolocation.

Steps to reproduce the problem:
Disable Geolocation when entering the app. 
Type in "What are you looking for"

**Comment by kikipluche** [comment]
related to

**Comment by kikipluche** [comment]
relates to #244
