### ISSUE TITLE
adding to homescreen

### ISSUE THREAD

**Issue by kikipluche** [swarmcity/sc-boardwalk#229]
When adding to homescreen (on android), the icon is not showing. Probably has something to do with the build...

**Comment by sophiii** [comment]
is this with chrome on iphone?

**Comment by QueenBeeSC** [comment]
The logo appears on my home screen on Android chrome. 
![screenshot_20170608-200957](https://user-images.githubusercontent.com/17633374/26955731-a9f90492-4c86-11e7-8f53-e564bf169a50.jpg)
