### ISSUE TITLE
Geolocation only works for 5 and 40km range

### ISSUE THREAD

**Issue by BvL13** [swarmcity/sc-boardwalk#234]
Actual behavior:
Geolocation only sees requests when set in the 5 or 40 km range. Requests outside this range cannot be seen even if the slider is set larger than 40 km or even to worldwide.
Requests even disappear when slider is set larger than 40 km.

Expected behavior:
Range slider changes the amount of requests I can see based on the real distance. Worldwide should reveal all requests there are.

Steps to reproduce the problem:
Create a deal. Move slider to any range available and watch the requests you placed.

**Comment by sponnet** [comment]
I can reproduce the problem here. Will look at it.

**Comment by sponnet** [comment]
was a minor thing in the whisper topic listeners. I think this is fixed now.
