### ISSUE TITLE
geofencing usability

### ISSUE THREAD

**Issue by kikipluche** [swarmcity/sc-boardwalk#236]
Actual behavior:
https://swarmcity.slack.com/files/bernd/F5QKQDBLN/bildschirmfoto_2017-06-07_um_09.06.53.png

When i hover with my mouse over the "In your area" part only the text is enabled to click, but the small arrow is disabled.
Also it's not a mouseover, but a cursor when pointing at the word.

Expected behavior:
Arrow and Text should be clickable and reveal the slider
become arrow on mouse over

Steps to reproduce the problem:
go to #boardwalktesting > open the slider

**Comment by n3xco** [comment]
Previous pull requests made the cursor a pointer on hover, pull #271 makes the triangle toggle the slider too (I forgot to add in previous pull request).
