### ISSUE TITLE
cancel my request as long as i haven't selected a provider

### ISSUE THREAD

**Issue by kikipluche** [swarmcity/sc-boardwalk#238]
Actual behavior:
i cannot cancel my requests 

Expected behavior:
being able to cancel my request as long as I haven't selected a provider

Steps to reproduce the problem:

**Comment by kingflurkel** [comment]
@faffydee can u visualize this?

**Comment by sponnet** [comment]
- [ ] save the details of the deal on an IPFS hash
- [ ] Emit event NewDealForTwo(<ipfs hash>,<owner>,...)
- [ ] Listener op Blockchain that lists your deals ( even after whisper messages have expired )
- [ ] Populate list 'my deals' from both shh traffic + blockchain listener
- [ ] on-tap on item -> go to dealfortwoseeker
- [ ] in dealfortwoseeker : cancel button + confirm screen
- [ ] if cancel pressed , do cancel transaction and return to hashtag list view
- [ ] in list-item 'this deal has been canceled'

**Comment by rodney757** [comment]
Is there a plan to migrate the existing deals to the new DealForTwoFactory contract when it's deployed? Or do we need to decode the input params of the existing contract makeDealForTwo transactions to retrieve the dealid so we can display them in the ui and allow users to accept,payout, or cancel the deal?

**Comment by kingflurkel** [comment]
![img_0038](https://user-images.githubusercontent.com/2879379/27760200-f6f5937e-5e41-11e7-958d-11d462fda607.PNG)
![img_0039](https://user-images.githubusercontent.com/2879379/27760199-f6f091bc-5e41-11e7-9242-2c1d6cbc4a47.PNG)

**Comment by kingflurkel** [comment]
![img_0038](https://user-images.githubusercontent.com/2879379/27760212-36a61a16-5e42-11e7-8d99-9f1d74a2cf49.PNG)
![img_0039](https://user-images.githubusercontent.com/2879379/27760213-36cd338a-5e42-11e7-9c9d-d3454d0d879a.PNG)
