### ISSUE TITLE
show commission fee

### ISSUE THREAD

**Issue by kikipluche** [swarmcity/sc-boardwalk#243]
@faffy_dee - in sc-hashtag.html , I put the visualisation of the hashtag commission in a tag. I plced it in comments ( see https://github.com/swarmcity/sc-boardwalk/blob/master/src/sc-hashtag/sc-hashtag.html#L367 ) - somehow the hashtag commission should be displayed before a user creates a deal, because the newitem submit button will remain disabled as long as your offer is lower than the commission...

and right now there is no place where the hashtag commission is displayed to the user in the app
so you can only guess what the error is

**Comment by sophiii** [comment]
This is fixed. plz close
