### ISSUE TITLE
Avatar and nickname dissapear after logout

### ISSUE THREAD

**Issue by matrixator** [swarmcity/sc-boardwalk#245]
Actual behavior: After I upload the avatar picture and complete the nickname, it shows up only if I click on the avatar placeholder. Also, after I logout and login, they dissappear altogether.

Expected behavior: Once set, the avatar picture and the nickname should remain in place even after logout.

Steps to reproduce the problem: Set an avatar picture and a nickname, logout, login.

**Comment by bkawk** [comment]
These need saving and retrieving from local storage

**Comment by kikipluche** [comment]
cannot reproduce the error, asked @matrixator
