### ISSUE TITLE
ARC conversion remains in limbo if you don't have ETH from the start

### ISSUE THREAD

**Issue by matrixator** [swarmcity/sc-boardwalk#246]
Actual behavior: 
If I have ARC in the wallet, but no ETH, it says I need ETH for the conversion. I send ETH to the wallet, and try to convert, it gets stuck even though the ETH is there. ( Error: Insufficient funds. The account you tried to send transaction from does not have enough funds. Required 21494734498832293216433030577863091147882 and got: 300000000000000000 )
"Restart the process" doesn't work, even after deleting account and restoring from a file or IPFS, it still remains stuck.

Expected behavior: 
After the wallet gets some ETH it should convert the ARC tokens. 

Steps to reproduce the problem: 
Send ARC tokens in an empty wallet, try to convert to SWT, send ETH, try to convert to SWT.

**Comment by sophiii** [comment]
@matrixator is this fixed https://swarmcity.slack.com/archives/G5N8W912L/p1496896318914950

**Comment by matrixator** [comment]
My ARC token got unstuck with the new version of software, but there was already ETH in the wallet. I wonder what  happends if someone replicates what I did (send ARC tokens in an empty wallet, try to convert to SWT, send ETH, try to convert to SWT). I can't try it now, but I'll try it later and write a feedback.

**Comment by matrixator** [comment]
I recreated the scenario - the bug is not gone. 

If someone tries to convert ARC to SWT without having ETH in the account, the ARC will get stuck. Sending ETH to the account afterwards doesn't solve the issue.

![image](https://user-images.githubusercontent.com/18177240/26931106-1629e3f8-4c68-11e7-891b-0ec23b8c2eea.png)

**Comment by sophiii** [comment]
nice, i am looking at this bug now :)

**Comment by sponnet** [comment]
Did you verify that this fix solves the problem ? ( You are converting BigNumber to a Number , but I think the function accepts a BigNumber .)
It doesn't look wrong , and if it fixes the behavior - I can merge this. Please let me know if you verified this.
