### ISSUE TITLE
"In your area" default shows no offers.  Value not persisted between page loads.

### ISSUE THREAD

**Issue by p-s-dev** [swarmcity/sc-boardwalk#254]
Actual behavior:
Each time I reload the page, I need to reset "In your area" to a value that will show some offers

Expected behavior:
Option 1. Dynamically set "In your area" to a value that will show some number of offers
Option 2. Remember the value I set for "In your area" and use that when I login again

Steps to reproduce the problem:
Login.  Change "In your area" to Worldwide.  Reload the page.  "In your area" is set to "+/-40km" and shows no offers for my area.

**Comment by bkawk** [comment]
Option 2 would be simple to create by storing and retrieving the value from localstorage

**Comment by kingflurkel** [comment]
Important: geo range should be saved per hashtag / not for the entire "app"

**Comment by n3xco** [comment]
Solving #254 And after @sponnet created range persistence in localstorage. @kingflurkel requested the ability to define a default range/hashtag (and a default).

Range selector now defaults to the hashtag default unless localstorage has a different value.

**Comment by kikipluche** [comment]
@kingflurkel

**Comment by kingflurkel** [comment]
ty xavier!
