### ISSUE TITLE
convert ARC=>SWT incorrect out of gas error 

### ISSUE THREAD

**Issue by kikipluche** [swarmcity/sc-boardwalk#255]
Actual behavior:
I have enough ETH in my wallet, but it gives an error out of gas

Expected behavior:
should go through

Steps to reproduce the problem:
send ARC to wallet and try to cenvert to SWT

**Comment by sophiii** [comment]
I think this has been fixed in the latest changes. https://swarmcity.slack.com/archives/G5N8W912L/p1496896318914950 

Does this issue still exist?

**Comment by sophiii** [comment]
Can you check this branch and confirm it solves this https://github.com/swarmcity/sc-boardwalk/pull/257 ?

**Comment by sophiii** [comment]
closeing in favor of https://github.com/swarmcity/sc-boardwalk/pull/267
