### ISSUE TITLE
Does not allow me to change from the current minimum offer

### ISSUE THREAD

**Issue by sophiii** [swarmcity/sc-boardwalk#259]
Actual behavior:
App only let me make offers equal to the request. 

Expected behavior:
I should be able to make a counter offer lower than the current offer. But t

Steps to reproduce the problem:
http://philatist-monkey-30658.netlify.com/#/hashtag/0xAB2b656cea9D351243A1742e5805Cfb9385feB24/list and try to create a counter offer.

**Comment by kingflurkel** [comment]
Yes, this is by design. Later on we will have the negotiation.
