### ISSUE TITLE
When I reload the page on dealfortwo-seeker, the info is gone

### ISSUE THREAD

**Issue by kikipluche** [swarmcity/sc-boardwalk#264]
Actual behavior:

Expected behavior:

Steps to reproduce the problem:

**Comment by sponnet** [comment]
the whisper (sc-shh) filters at sc-listeners kick in when the user arrives at the route /hashtag/<address of hashtag contract>/list and are disabled when that route is left to save on costly network polling of the Ethereum node.
The dealfortwo-seeker routes are on another path - disabling the sc-listeners fo rthat route. If you reload, these listeners are not activated.
So

- [ ] move sc-dealfortwo-provider & sc-dealfortwo-seeker in sc-hashtag
- [ ] create a neon-animatable page
- [ ] show the hashtag list template on /hashtag/<address>/list
- [ ] show the sc-dealfortwo-provider on /hashtag/<address>/dealfortwoprovider/<extra data>
- [ ] show the sc-dealfortwo-seeker on /hashtag/<address>/dealfortwoseeker/<extra data>
- [ ] withstand the rant of Faffydee when he has to fix the CSS animations on this puppy



moving the sc-dealfortwo-provider and -seeker into the sc-hashtag + a routing switch there could solve this

**Comment by sponnet** [comment]
unfixable in current approach
