### ISSUE TITLE
Lingering SWT value from previous offer

### ISSUE THREAD

**Issue by QueenBeeSC** [swarmcity/sc-boardwalk#269]
## Environment
OS, Browser, Version

Android, Chrome

## Actual behavior:
After successfully publishing an offer, when I return to create a new offer the SWT amount is still present from the previous offer.

## Expected behavior:

 No lingering details from previous offers

## Steps to reproduce the problem:
Create an offer.  Publish it.  Go back to the boardwalk and place a new offer. The previous SWT value is still present. 

## Console Output (if possible):

Go to developer tools, and select Console copy the Output below 

```
Output
```

**Comment by sponnet** [comment]
in sc-newitem there should be a reset function , that clears all the paper-textarea and paper-input fields.

this function this.$.newitem.reset() should be called fromthe on-tap event of that component

**Comment by QueenBeeSC** [comment]
Users must delete the restored SWT value to proceed... this causes the inactive blue check mark.
