### ISSUE TITLE
dealfortwo seaker payout: X SWT has been payed out to

### ISSUE THREAD

**Issue by kikipluche** [swarmcity/sc-boardwalk#278]
## Actual behavior:
is the amount + half of the commission fee

## Expected behavior:
the SWT has been payed out, should be the amount - half of the commission fee.

```
Output
```

**Comment by sponnet** [comment]
![image](https://user-images.githubusercontent.com/596726/26978675-a5e187f2-4d2c-11e7-82b6-be1f78ebaa35.png)
seems fixed..
