### ISSUE TITLE
no option to create json download backup on Windows 10 Chrome browser.

### ISSUE THREAD

**Issue by kikipluche** [swarmcity/sc-boardwalk#290]
## Environment
Windows 10 chrome

## Actual behavior:
no option to create json download backup 

## Expected behavior:
be able to make json backup

## Console Output (if possible):
Go to developer tools, and select Console copy the Output below 

```
Output
```

**Comment by sponnet** [comment]
in some browsers ( safari ) , client side JSON downloading cannot be achieved. There we only give the option to backup to IPFS.
I'm not sure why he shows no download possibility in windows 10.

The code for verifying the availability of file downloading is here 

https://github.com/swarmcity/sc-boardwalk/blob/master/src/sc-vault/sc-vault.html#L1057

Can the reporter check what the code does with his browser ? Why does he evaluate this.download_backup_available to be false ?
