### ISSUE TITLE
mobile view SWT is missing 

### ISSUE THREAD

**Issue by kikipluche** [swarmcity/sc-boardwalk#303]
## Environment
mobile S7

## Actual behavior:
the letters SWT are missing
<img width="487" alt="screen shot 2017-06-11 at 13 56 57" src="https://user-images.githubusercontent.com/9036081/27010820-f8c8838a-4ead-11e7-9755-b3f29a174901.png">

## Expected behavior:
currency SWT is next to the amount

## Steps to reproduce the problem:
on mobile, #view 

## Console Output (if possible):
Go to developer tools, and select Console copy the Output below 

```
Output
```

**Comment by faffydee** [comment]
It's by design: when the viewport is getting small, we reduce the visual information on a page: e.g. the 'swt'-letters, the username... because of a lack of width, to keep the ui clean over overviewable.
