### ISSUE TITLE
Transaction should expire in a certain ammount of time, if the selected provider doesn't answer

### ISSUE THREAD

**Issue by matrixator** [swarmcity/sc-boardwalk#315]
## Environment
Not relevant

## Actual behavior:
When I select a provider and he doesn't reply, the transaction remains there forever (?)

## Expected behavior:
If the provider doesn't answer in 30 seconds, the transaction should expire, so the requester can select another provider.

## Console Output (if possible):
Go to developer tools, and select Console copy the Output below 

```
Output
```

**Comment by kikipluche** [comment]
we will provide a cancel button.
