### ISSUE TITLE
timeframe whisper messages.

### ISSUE THREAD

**Issue by kikipluche** [swarmcity/sc-boardwalk#322]
put it to 5 days

**Comment by sponnet** [comment]
in these files
- src//sc-dealchat/sc-dealchat.html
- src//sc-dealfortwo/sc-dealfortwo-provider.html
- src//sc-dealfortwo/sc-dealfortwo-seeker.html
- src//sc-dealfortwo/sc-dealfortwo.html
- src//sc-itemdetail/sc-itemdetail.html
- src//sc-itemreplier/sc-itemreplier.html
- src//sc-itemreply/sc-itemreply.html
- src//sc-newitem/sc-newitem.html

Replace  "ttl": 60 * 60 * 24 in the body with this.config.shhttl or self.config.shhttl where applicable

**Comment by kikipluche** [comment]
@sponnet kan je der 1 week van maken
