### ISSUE TITLE
put deals on ipfs, to have backup after dissapearing from whisper.

### ISSUE THREAD

**Issue by kikipluche** [swarmcity/sc-boardwalk#323]
all my done deals: encrypt and put to ipfs, all parameters so they can be gathered back
all my created deals
all my funded deals
all my cancelled deals 

I want to see all the deals that I created and all deals I am involved with, even if is not on whisper anymore.

**Comment by rodney757** [comment]
I would be interested in taking this on if @sponnet hasn't started work on this. I was talking with @joshuam10o on slack the other day about this and just realized this was an issue.

**Comment by kingflurkel** [comment]
This issue needs to be solved in a different way; only the negotiation should go over whisper. Done deals should come in the redux by reading out the deals on the hashtagcontract.
