### ISSUE TITLE
tekst in infobutton #pioneer

### ISSUE THREAD

**Issue by kikipluche** [swarmcity/sc-boardwalk#331]
'_{{Pioneer}}_' (_{{contracthash}}_) is maintained by _{{maintainer_name}}_ ( _{{maintainer_pubkey}}_ )
The hashtagcommission is 0.005 SWT

Contact:
support.swarm.city
slack: https://swarmcity.slack.com/messages/C3KQES5NV/convo/G5N8W912L-1497462162.062389/

**Comment by faffydee** [comment]
to add:
- {{contractname}}
- {{contracthash}}
- {{maintainer_name}}
- {{maintainer_pubkey}}
