### ISSUE TITLE
Able to reply to myself after renaming my avatar

### ISSUE THREAD

**Issue by bobsuruncle2000** [swarmcity/sc-boardwalk#346]
## Environment
Win10, Chrome, Latest

## Actual behavior:
Posted a request on # Pioneer as "nickname"
Renamed to "bobsuruncle"
Was able to reply to my own request

## Expected behavior:
Should not be able to reply to myself

## Steps to reproduce the problem:
Create wallet on Swarm.city
Post request
Rename avatar
Reply to your own post

## Console Output (if possible):

```
Output
```

**Comment by kingflurkel** [comment]
@sponnet can you give some feedback on this? Frontend only issue or also in Solidity?

**Comment by kingflurkel** [comment]
#304
