### ISSUE TITLE
iOS password crash

### ISSUE THREAD

**Issue by joshuam10o** [swarmcity/sc-boardwalk#347]
## Environment
OS, Browser, Version
iOS 7, Chrome + Safari

## Actual behavior:
When typing in a password, the browser crashes

## Expected behavior:
When typing in a password, it does not crash

## Steps to reproduce the problem:
Begin typing in a  password after opening the app

## Console Output (if possible):
Go to developer tools, and select Console copy the Output below 

```
Output
```

**Comment by kikipluche** [comment]
@joshuam10o Can you reproduce this? I can not.

**Comment by joshuam10o** [comment]
Likely duplicate of #192 @kikipluche, we can probably close this.
