### ISSUE TITLE
GUI: Ether Balance On Profile Page Has NoSpaces Before / After

### ISSUE THREAD

**Issue by taoteh1221** [swarmcity/sc-boardwalk#359]
## Environment
Win10/Chrome

## Actual behavior:
You currently haveX.XXetheron this profile.

## Expected behavior:
You currently have X.XX ether on this profile.

## Steps to reproduce the problem:
Visit profile page (click user avatar)

## Console Output (if possible):
N/A

**Comment by n3xco** [comment]
This was an existing issue (#311), which we solved locally. Pull request #358 should fix this on the live website too.

**Comment by taoteh1221** [comment]
Cool, closing this then.
