### ISSUE TITLE
Prominent notice for new users regarding the need for ETH in their SWT wallet to transact

### ISSUE THREAD

**Issue by taoteh1221** [swarmcity/sc-boardwalk#365]
## Environment
Boadwalk GUI (non-platform specific)

## Actual behavior:
New users to the crypto ecosystem are not being alerted well enough with current GUI notices / error notices regarding the need for ETH to pay transaction fees: 

https://www.reddit.com/r/SwarmCity/comments/6hww8v/help_i_keep_getting_an_error_when_trying_to/dj1rov1/

https://www.reddit.com/r/SwarmCity/comments/6hjsv1/something_went_wrong_try_again/

https://www.reddit.com/r/SwarmCity/comments/6hxnlw/you_dont_have_enough_eth_to_post_a_new_request/

## Expected behavior:
New user realizes they need ETH in their SWT address to transact

## Steps to reproduce the problem:
Create a new account , fill with SWT, don't add any ETH, observe current error notices when attempting to transact

## Console Output (if possible):
N/A

**Comment by kikipluche** [comment]
will be solved with gasstation
