### ISSUE TITLE
general popup view for warnings and education

### ISSUE THREAD

**Issue by kikipluche** [swarmcity/sc-boardwalk#378]

**Comment by kingflurkel** [comment]
![img_0037](https://user-images.githubusercontent.com/2879379/27685782-00693686-5cd0-11e7-9fe2-9ae00946c489.PNG)

**Comment by faffydee** [comment]
Good idea, let's also create a general use of these warnings: e.g. when to do a warning and such

**Comment by kikipluche** [comment]
going to be incorporated in the V2
