### ISSUE TITLE
More intuitive hashtaglist communication 

### ISSUE THREAD

**Issue by joshuam10o** [swarmcity/sc-boardwalk#381]
## Environment
OS, Browser, Version

## Actual behavior:
Users have no communication with their selected provider/ providers have no communication with potential customers before they take on a financial risk in depositing into a deal. This can currently only be done "out of channel" such as on Slack and Twitter etc, reducing the "usefulness" of the app, if you are expected to leave the app over the course of a normal deal. 

## Expected behavior:
Users expect to be able to communicate with providers on the hashtaglist/dealitem because it looks like a forum/thread/comments section. Either provide a means of communication, or make it more apparent what the purpose of the hashtag list is (*only* offers and counteroffers). 

(I'm assuming that financial risk is more important than spamming risk) 

## Console Output (if possible):
Go to developer tools, and select Console copy the Output below 

```
Output
```

**Comment by kingflurkel** [comment]
By design
