### ISSUE TITLE
copy-paste migrate components

### ISSUE THREAD

**Issue by kikipluche** [swarmcity/sc-boardwalk#76]
Copy the components which can be migrated without any adjustments.

**Basically all component,  but NOT these:**
ac-swtconversion
ac-intro
ac-vault
ac-home
ac-profile
ac-walletview

**Comment by faffydee** [comment]
List of copy-pasted components:
Avatar
Balance
Password
Tokensend
Tokenreceive
shortcode
Ipfs
Ipfsupload 

sc-username was created new, it is sliced of sc-avatar to avoid confusion.
