### ISSUE TITLE
vault/unlock layout problem

### ISSUE THREAD

**Issue by kikipluche** [swarmcity/sc-boardwalk#82]
This style should be some loader or something ? Can u take a peek ?

![image](https://cloud.githubusercontent.com/assets/596726/23899307/eaf73f92-08b4-11e7-88a3-548037653e6d.png)

**Comment by sponnet** [comment]
Looks like this:


![image](https://cloud.githubusercontent.com/assets/596726/23898843/f8ca1ec0-08b2-11e7-830d-422bc28b13a2.png)
