### ISSUE TITLE
typo in Antoine Verdon

### ISSUE THREAD

**Issue by kikipluche** [swarmcity/sc-boardwalk#84]
It is an O instead of an U
<img width="467" alt="screen shot 2017-03-14 at 18 14 44" src="https://cloud.githubusercontent.com/assets/9036081/23913123/40ef2892-08e2-11e7-82ee-185b8b8c9493.png">

**Comment by commiteth** [comment]
![Contract deploying](https://commiteth.com/img/deploying_contract.png)
